soft deadline
NotWhaleee/OOP pull request #16
Opened 2024-03-07 10:59 UTC by NotWhaleee

2024-03-14 15:29 UTC, shadrina reviewed
Покажешь завтра вживую. Тяжеловато читается, нет четкой структуры.

2024-03-22 08:50 UTC, shadrina requested changes

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/BakersThreads.java
> +        if (pizzeria.orders >= 0) {
А когда оно может уйти в минус?

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/BakersThreads.java
> +                    if (startCooking(pizzeria, finalI)) {
Я не понимаю, почему ты разделяешь исполняемых Bakerов (`bakersThreads`) и "логических" (`pizzeria.bakers`). 
Из этой схемы у меня возникают вопросы:
1) Какая цель у этого разделения? Почему бы классу Baker не наследовать Thread (или не реализовать Runnable, а потом использовать для создания Thread)?
2) Когда `startCooking` может вернуть `false` и почему? Т.е. почему этот Baker с этим id занят, когда его может использовать единственный поток, для него созданный?

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/Main.java
> +package ru.kozorez;
Делай, пожалуйста, подпакеты, когда классов много и их можно логически разделить. Тогда в коде гораздо легче разбираться.

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/Main.java
> +package ru.kozorez;
Автору в том числе.

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/Pizzeria.java
> +            if (baker != null) {
А когда он может быть null?

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/Pizzeria.java
> +            if (baker != null) {
Аналогичный вопрос для курьеров

2024-03-22 08:50 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/kozorez/Pizzeria.java
> +        */
Почему закомментировано?

2024-03-23 09:07 UTC, NotWhaleee commented on Task_2_2_1/src/main/java/ru/kozorez/BakersThreads.java
> +        if (pizzeria.orders >= 0) {
не может, это рудимент :))

2024-03-23 09:24 UTC, NotWhaleee commented on Task_2_2_1/src/main/java/ru/kozorez/Pizzeria.java
> +            if (baker != null) {
в данной версии программы не может

2024-03-23 09:27 UTC, NotWhaleee commented on Task_2_2_1/src/main/java/ru/kozorez/Pizzeria.java
> +        */
была реализация с доготовкой заказов при закрытии пиццерии, сейчас заказы переносятся на следуюзий день

2024-03-23 10:27 UTC, NotWhaleee commented on Task_2_2_1/src/main/java/ru/kozorez/BakersThreads.java
> +                    if (startCooking(pizzeria, finalI)) {
2. start cooking возрвращает false, если не получилось взять заказ. про занятость baker и  courier поправил.

2024-03-29 06:49 UTC, shadrina reviewed
Вроде теперь норм, но надо вживую смотреть, как оно работает

2024-04-12 06:35 UTC, shadrina approved these changes

2024-04-15 17:19 UTC, merged