Task_1_1_1
NotWhaleee/OOP pull request #2
Opened 2023-09-15 05:13 UTC by NotWhaleee

2023-09-17 20:08 UTC, artromone commented
Looks good!

2023-09-26 09:00 UTC, shadrina requested changes
Посмотри варнинги во вкладке Files changed. Там есть замечания по существу.

2023-09-26 09:00 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        }
Давай все-таки случайными числами заполним, так будет честнее тест

2023-09-26 09:00 UTC, shadrina commented on Task_1_1_1/src/main/java/org/example/Heapsort.java
> +package org.example;
Пакет автогенерированный. Сделай свой.

2023-09-26 09:00 UTC, shadrina commented on Task_1_1_1/build.gradle
> +group = 'org.example'
Со сменой пакета поправь тут группу

2023-10-03 03:22 UTC, shadrina reviewed
Я засчитываю, но перед мерджем нужно поправить имя пакета и варнинги про документацию.

2023-10-03 14:55 UTC, merged